// export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST';
// export const UPLOAD_AND_GET_FILE_SUCCESS = 'UPLOAD_AND_GET_FILE_SUCCESS';
// export const UPLOAD_FILE_FAILURE = 'UPLOAD_FILE_FAILURE';
// export const GET_URL_FILE_FAILURE = 'GET_URL_FILE_FAILURE';

// export const ADD_IRREGULAR_VERBS_REQUEST = 'ADD_IRREGULAR_VERBS_REQUEST';
// export const ADD_IRREGULAR_VERBS_SUCCESS = 'ADD_IRREGULAR_VERBS_SUCCESS';
// export const ADD_IRREGULAR_VERBS_FAILURE = 'ADD_IRREGULAR_VERBS_FAILURE';

// export const GET_DATA_IRREGULAR_VERBS_PAGE_REQUEST = 'GET_DATA_IRREGULAR_VERBS_PAGE_REQUEST';
// export const GET_DATA_IRREGULAR_VERBS_PAGE_SUCCESS = 'GET_DATA_IRREGULAR_VERBS_PAGE_SUCCESS';
// export const GET_DATA_IRREGULAR_VERBS_PAGE_FAILURE = 'GET_DATA_IRREGULAR_VERBS_PAGE_FAILURE';
